### ISSUE TITLE
QA training set construction

### ISSUE THREAD

**Issue by MaxZhongSheep** [FudanDISC/DISC-LawLLM#16] opened 2023-10-26 11:20 UTC
Could you give me some examples about QA training set or more precisely how I can construct it?I am curious about it.

**Comment by Charlie-XIAO** [comment] 2023-10-29 03:04
xref #19, does that explanation suffice?

**Comment by Charlie-XIAO** [comment] 2023-10-29 03:11
Regardless, I'm closing this as a duplicate of #10.

**Closed** 2023-10-29 03:11 UTC
